
interface JobOffer {
  state: string;
  salary: string;
}

export const compareOffers = (offer1: JobOffer, offer2: JobOffer, homeState: string): string => {
  const weeklySalary1 = parseFloat(offer1.salary) || 0;
  const weeklySalary2 = parseFloat(offer2.salary) || 0;
  
  // Calculate annual salary (weekly * 52)
  const annualSalary1 = weeklySalary1 * 52;
  const annualSalary2 = weeklySalary2 * 52;

  // Check if we're analyzing one or two destinations
  const isSingleDestination = !(offer1.state && offer1.salary && offer2.state && offer2.salary);
  
  if (isSingleDestination) {
    // Analyze the single destination that has data
    const offer = offer1.state && offer1.salary ? offer1 : offer2;
    const weeklySalary = parseFloat(offer.salary) || 0;
    const annualSalary = weeklySalary * 52;
    
    return `TRAVEL CONTRACT ANALYSIS
=============================

CONTRACT DESTINATION
------------------------------
Location: ${offer.state}
Weekly Pay: $${weeklySalary.toLocaleString()}
Annual Pay (52 weeks): $${annualSalary.toLocaleString()}

HOME STATE INFORMATION
------------------------------
Home State: ${homeState}
${homeState !== offer.state ? `- Living in a different state than your tax home (${homeState}) may affect your eligibility for tax-free stipends.` : "- Since your contract location is the same as your tax home, you may not qualify for tax-free stipends."}

ADDITIONAL CONSIDERATIONS
------------------------------
- Research the cost of living in ${offer.state}
- Consider state income tax rates (some states have no income tax)
- Factor in housing costs in ${offer.state}
- Evaluate healthcare costs in ${offer.state}
- Consider climate preferences and quality of life
- Research job market stability in ${offer.state}
- Factor in potential relocation costs if applicable

Report generated by Plovrr on: ${new Date().toLocaleDateString()}
`;
  } else {
    // Compare two destinations
    return `TRAVEL CONTRACT COMPARISON REPORT
=============================

CONTRACT DESTINATION 1
------------------------------
Location: ${offer1.state}
Weekly Pay: $${weeklySalary1.toLocaleString()}
Annual Pay (52 weeks): $${annualSalary1.toLocaleString()}

CONTRACT DESTINATION 2
------------------------------
Location: ${offer2.state}
Weekly Pay: $${weeklySalary2.toLocaleString()}
Annual Pay (52 weeks): $${annualSalary2.toLocaleString()}

HOME STATE INFORMATION
------------------------------
Home State: ${homeState}
${homeState !== offer1.state || homeState !== offer2.state ? `- Living in a different state than your tax home (${homeState}) may affect your eligibility for tax-free stipends.` : ""}

COMPARISON SUMMARY
------------------------------
Weekly Pay Difference: $${Math.abs(weeklySalary1 - weeklySalary2).toLocaleString()} ${
    weeklySalary1 > weeklySalary2
      ? `(Destination 1 pays more)`
      : weeklySalary2 > weeklySalary1
      ? `(Destination 2 pays more)`
      : "(Equal pay)"
  }

Annual Pay Difference: $${Math.abs(annualSalary1 - annualSalary2).toLocaleString()}

Location Comparison: ${offer1.state} vs. ${offer2.state}
${
  offer1.state !== offer2.state
    ? `- Consider cost of living differences between ${offer1.state} and ${offer2.state}`
    : ""
}
${
  offer1.state !== offer2.state
    ? "- Research state tax implications for each location"
    : ""
}

ADDITIONAL CONSIDERATIONS
------------------------------
- Research the cost of living in each location
- Consider state income tax rates (some states have no income tax)
- Factor in housing costs in each state
- Evaluate healthcare costs in each state
- Consider climate preferences and quality of life
- Research job market stability in each state
- Factor in potential relocation costs if applicable

Report generated by Plovrr on: ${new Date().toLocaleDateString()}
`;
  }
};
